CC = gcc

#all: list lists queues stacks
all:  glists dlists queues stacks sets 

$(all) :   
	$(CC) -c -g3 lists.c

clean:
	rm gen_llist.o gen_queues.o gen_stacks.o lists.o gen_sets.o double_llist.o dlists
