CFLGAS= -g3
CC = gcc

all = is_polindrome

is_polindrome: is_polindrome.o
	$(CC) -o is_polindrome is_polindrome.o

is_polindrome.o : is_polindrome.c
	$(CC) -c -g3 is_polindrome.c

clean:
	rm is_polindrome is_polindrome.o


