CFLGAS= -g3
CC = gcc

all = is_polindrome

is_polindrome: is_polindrome.o
	$(CC) -o is_polindrome is_polindrome.o

is_polindrome.o : is_polindrome.c
	$(CC) -c -g3 is_polindrome.c
str_permute: str_permute.c
	$(CC) -o str_permute str_perumte.c
clean:
	rm is_polindrome is_polindrome.o str_permute


